### PR TITLE
Audio: Ensure Voice handle exists before stopping it

### PR DESCRIPTION
**Pull request by myst6re**
## Summary

Fix sudden stop of musics, for example in Fisherman Horizon Concert, when the dialog starts with Rinoa next to the stage.

### ACKs

- [X] I have updated the [Changelog.md](https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md) file
- [ ] I did test my code on FF7
- [X] I did test my code on FF8

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Interesting patch, how fixing the voice layer fixes also the music part?

**Comment by myst6re** [comment]
I think doing stopMusic on an invalid handler could stop group handlers, those kind of handler I use only in FH concert to synchronize tracks together

**Comment by myst6re** [comment]
Also group handle is considered as invalid by soloud, and cannot be used to stop a music, so maybe internally soloud does not check the handle when you stop the music and find the voice of the group handle instead of doing nothing

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Makes sense. Thanks a lot :)

**Pull request merged**
