### PR TITLE
Widescreen: Avoid clipping world Y position for FIELD mode world script movements

### LINKED ISSUE #474: [ FF7 ] Collection of widescreen 16:9 bugs
This is the collection of bugs related to the new widescreen 16:9 aspect ratio mode.

**Common**
- [x] 16:9 aspect ratio stretches to fill the screen when displayed on an ultrawide monitor

**Field mode**
- [ ]  Some fields show a back bar on the top/bottom of the screen
- [ ]  The chocobo black screen in the Chocobo Farm does not show
- [ ]  The wind overlay in Gaea's cliff does not scale to fill the screen
- [ ]  In fship_22, the vertical scrolling stops too early
- [ ] Aerith's Great Gospel Limit 4 shows the black background in the edges

**Battle mode**
- [ ] Compact Battle UI has black background on the bottom right and left
- [x] Limit break boxes extend beyond the intended window
- [ ] Pollensalta at Northern Cave - The full screen spell texture is not following true widescreen

**Worldmap mode**

**Other modes**
- [x] shop characters/text to appear cut off
- [ ]  Condor minigame is still 4:3

Before reporting new bugs/glitches, make sure you are running the latest canary version of FFNx. Also double check if the bug or glitch is not already in this list

### PR DESCRIPTION
**Pull request by tangtang95**
## Summary

Fix #474 chocobo issue and fship_22 camera movement

### ACKs

- [ ] I have updated the [Changelog.md](https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md) file
- [x] I did test my code on FF7
- [ ] I did test my code on FF8

### CODE REVIEW

**Comment by tangtang95** [comment]
Wait, it seems there is another scene that has to be tested

**Comment by tangtang95** [comment]
The scene seems fine.

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by tangtang95** [comment]
Sorry, changed the commit message since it was kinda misleading

**Comment by tangtang95** [comment]
There are actually issue with a scene. But not really sure if it can be fixed easily

**Comment by tangtang95** [comment]
I think it can be merged now. If there are other issues, it will be fixed next time

**Comment by tangtang95** [comment]
Sorry, had a misunderstanding with what Cosmos wrote, now, the solution should be better.

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Thank you!

**Pull request merged**
