### PR TITLE
changed GetCurrentDirectoryA to GetCurrentDirectory

### PR DESCRIPTION
**Pull request by Sebanisu**
sithlord48 was testing on linux under wine and for some reason GetCurrentDirectoryA didn't work but we changed to GetCurrentDirectory and it is working now.

### CODE REVIEW

**Comment by sithlord48** [comment]
After the change I am now able to load the external music and my mods from my mod patch

**Comment by julianxhokaxhiu** [comment]
Oh I see! I think this PR is not required at all. You may probably just need an [hard link](https://en.wikipedia.org/wiki/Hard_link) and you should be good to go :)

**Comment by Sebanisu** [comment]
Standard library to maybe get full Unicode and text transcoding in cpp23. There was a talk at cppcon 2019 about it

**Comment by julianxhokaxhiu** [comment]
That's too far away but I think it makes sense. Thanks for letting me know!

**Pull request closed without merging**
