### PR TITLE
Voice: Fix pause and music fadeout logics

### PR DESCRIPTION
**Pull request by tangtang95**
Try to see if the pause truly does not work. I tried it and it seems that after pausing the voice was still going a little. Then after resuming it started a lot afterwards

### CODE REVIEW

**Comment by tangtang95** [comment]
Still need to decide the filename based on the dialog text of sense, steal and other command that display text. For example, in sense there are 2 or 3 display texts and from what I saw, there is no need to substitute any enemy name or item. So, need to distinguish the different display text using maybe a substring?

**Review by julianxhokaxhiu — APPROVED** [review]
LGTM

Is there anything else pending on this? Looks like feature complete to me. Thanks for fixing the pause as well, I totally forgot you had a section ready for that, my bad!

**Comment by tangtang95** [comment]
As I said, sense, steal, and the other commands needs some tweak to work well. If you want you can merge for now

**Comment by julianxhokaxhiu** [comment]
Thank you :)

**Pull request merged**
