### PR TITLE
Adding Winamp plugin support (FF7Music will be obsolete after this)

### PR DESCRIPTION
**Pull request by myst6re**
Trying to reproduce FF7Music behavior, without FF7Music.

Motivation: currently PSF files are not supported by vgmstream. In fact the only known support of this format is a winamp plugin (Highly Experimental, in_psf.dll).

This PR enables support for any winamp in/out plugin (hopefully).

### CODE REVIEW

**Comment by myst6re** [comment]
How to use with Highly Experimental (PSF) Winamp plugin:
 - Copy in_psf.dll along with FFNx files in ff7 installation dir
 - Create a file "plugin.ini" with the following content:
```
[HighlyExperimental]
EnableMain=1
EnableReverb=1
SimulateFrequencyResponse=1
EmuShowCPUUsage=1
JinxIsAGoodBoy=1
TitleFormat=%game% - %title%
TitleFormatFallback=%filename%
ForceIndefinite=1
DefaultLength=2:50
DefaultFade=10
SuppressOpeningSilence=1
SuppressEndingSilence=1
EndingSilenceSeconds=5
ThreadPriority=2
GlobalVolume=1.9953
SoftSaturate=1
Resample=0
ResampleFreq=44100
ReplayGainEnable=1
ReplayGainAlbum=1
ClipProtectEnable=1
ClipProtectAlbum=0
StrictFormatChecking=0
ShowErrorMessages=0
```
- Put your PSF files (with correct names, see FFNx manual) and the linked *.psflib file in the music directory
- Edit FFNx.cfg and change `use_external_music` to `3` (check the comments to ensure this value correspond to the winamp plugin). Set your music directory path with `external_music_path`. And set `external_music_ext` to the correct extension of your psf files (`minipsf` or `psf`). Finally, set `in_plugin_dll_name` option with the dll name.

**Comment by myst6re** [comment]
TODO list:
 - setTempo is not implemented for Winamp out plugin, dunno how to implements it (maybe using Play() with modified parameters, but it will pause the music a little I think)
 - check if music resume correctly without reset each time we have a battle
 - refactoring: some code in vgmtream and winamp are common
 - test test test

**Comment by myst6re** [comment]
I updated my previous TODO-list, I have new items to add:
 - [DONE] use in_vgmstream implementation
 - Ensure non-looping songs are correctly stopped (good night for example)
 - Improving fading
 - Fix relative long pause issue when seeking to the end of main theme

**Comment by julianxhokaxhiu** [comment]
Amazing work! Thank you :)

**Pull request merged**
