### PR TITLE
FF8: Gamepad input/rendering fixes

### PR DESCRIPTION
**Pull request by myst6re**
## Summary

Fix analog direction for DirectInput (legacy) controllers

### ACKs

- [X] I have updated the [Changelog.md](https://github.com/julianxhokaxhiu/FFNx/blob/master/Changelog.md) file
- [ ] I did test my code on FF7
- [X] I did test my code on FF8

### CODE REVIEW

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Can you please rebase against master? Thank you :)

**Comment by julianxhokaxhiu** [comment]
Can you please rebase? Thank you :)

**Comment by myst6re** [comment]
> Can you please rebase? Thank you :)

Done

**Comment by julianxhokaxhiu** [comment]
There's a build issue for some reason, can you please have a look?

**Comment by myst6re** [comment]
> There's a build issue for some reason, can you please have a look?

Bad merge sorry, it builds

**Review by julianxhokaxhiu — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
Thank you!

**Pull request merged**
