### PR TITLE
FF7: allow to play oa (opening music) from external music instead of the movie

### PR DESCRIPTION
**Pull request by myst6re**

### CODE REVIEW

**Comment by myst6re** [comment]
Tested and ready

**Review by julianxhokaxhiu — CHANGES_REQUESTED** [review]
The PR code wise looks good to me. I'm just a bit conflicted on the flag name. What about `ff7_external_opening_music` instead?

**Comment by myst6re** [comment]
> The PR code wise looks good to me. I'm just a bit conflicted on the flag name. What about `ff7_external_opening_music` instead of `ff7_play_opening_music`? Also, what does the PR does in concrete? Looks like it disables the `ob` playback, but it's not clear to me what it does overall.

The PC game does not plays the oa song. In fact the music is directly mixed into the intro movie. To makes it work, the developer has hardcoded a deactivation of oa when the field script tries to play it. And when the movie frame has reached one specific frame, it plays the ob track.

My PR disable this hack, so now the field script plays the oa only for the introduction, and ob when necessary.

> `ff7_play_opening_music`

No problem :) done!

**Review by julianxhokaxhiu — APPROVED** [review]
Thank you. All clear :) LGTM

**Pull request merged**
