### PR TITLE
Fix Cid speech music resume bug

### PR DESCRIPTION
**Pull request by myst6re**

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Hey thanks! Can you please rebase your branch? You miss one required to build successfully :) Thank you!

**Comment by myst6re** [comment]
Sorry, but it is already up to date, if you removed commits or modified an existing one, that's completely invisible to me :)

**Comment by julianxhokaxhiu** [comment]
Ah sorry, the issue is something else! It's because PRs do have a version number + letters, and this makes the version manifest go crazy...I'll try to figure out a way to consider this as devel so it doesn't go crazy. Let me fix it and then I'll ask you to rebase again! Thank you in advace

**Comment by julianxhokaxhiu** [comment]
Allright, can you please rebase now?

**Comment by myst6re** [comment]
> 
> 
> Allright, can you please rebase now?

Sure, done!

**Comment by julianxhokaxhiu** [comment]
As always thank you!

**Pull request merged**
